# Generated by Django 4.1 on 2024-06-06 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='altezza',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_pic',
        ),
    ]
