# Generated by Django 4.1.7 on 2023-05-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_goalmodel_data_creazione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalmodel',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
