# Generated by Django 4.1.7 on 2023-05-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_alter_goalmodel_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalmodel',
            name='status',
            field=models.CharField(choices=[('V', 'In Corso'), ('S', 'Scaduto')], default='V', max_length=1),
        ),
        migrations.AlterField(
            model_name='goalmodel',
            name='tempistica',
            field=models.IntegerField(choices=[(7, '1 settimana'), (30, '1 mese'), (90, '3 mesi')], default=30),
        ),
    ]
