# Generated by Django 4.1.7 on 2023-06-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_goalmodel_caloriesgoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalmodel',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goalmodel',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
