# Generated by Django 4.1.7 on 2023-06-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0008_goalmodel_cal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalmodel',
            name='CaloriesGoal',
            field=models.IntegerField(default=0),
        ),
    ]
