# Generated by Django 4.1.7 on 2023-06-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0009_alter_goalmodel_caloriesgoal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalmodel',
            name='tempistica',
            field=models.IntegerField(choices=[(1, '1 giorno'), (7, '1 settimana'), (30, '1 mese'), (90, '3 mesi')], default=30),
        ),
    ]
