# Generated by Django 4.1.7 on 2023-06-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0010_alter_goalmodel_tempistica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalmodel',
            name='goal_type',
            field=models.CharField(choices=[('Weight Loss', 'Weight Loss'), ('Muscle Gain', 'Muscle Gain'), ('Fitness Improvement', 'Fitness Improvement')], max_length=20),
        ),
        migrations.AlterField(
            model_name='goalmodel',
            name='tempistica',
            field=models.IntegerField(choices=[(1, '1 day'), (7, '1 week'), (30, '1 month'), (90, '3 months')], default=30),
        ),
    ]
