# Generated by Django 4.1.7 on 2023-05-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obiettivi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalmodel',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='goalmodel',
            name='status',
            field=models.CharField(choices=[('V', 'Valido'), ('S', 'Scaduto'), ('D', 'Da fare')], default='V', max_length=1),
        ),
        migrations.AddField(
            model_name='goalmodel',
            name='tempistica',
            field=models.IntegerField(choices=[(7, '1 settimana'), (30, '1 mese'), (90, '3 mesi')], default=7),
        ),
    ]
