# Generated by Django 4.1.7 on 2023-06-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obiettivi', '0005_alter_goalmodel_status_alter_goalmodel_tempistica'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalmodel',
            name='CaloriesGoal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
