# Generated by Django 4.1.7 on 2023-06-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obiettivi', '0007_goalmodel_is_completed_goalmodel_is_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalmodel',
            name='cal',
            field=models.IntegerField(default=0),
        ),
    ]
