# Generated by Django 4.1.7 on 2023-06-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obiettivi', '0011_alter_goalmodel_goal_type_alter_goalmodel_tempistica'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalmodel',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
