# Generated by Django 4.1.7 on 2023-05-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duration', models.DurationField()),
                ('calories_burned', models.IntegerField()),
                ('workout_type', models.CharField(choices=[('corsa', 'Corsa'), ('pesi', 'Pesi'), ('cyclette', 'Cyclette')], max_length=20)),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
