# Generated by Django 4.1.7 on 2023-05-24 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='duration',
        ),
    ]
