# Generated by Django 4.1.7 on 2023-05-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_remove_workout_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='descrizione',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='workout',
            name='repetitions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='workout_type',
            field=models.CharField(choices=[('corsa', 'Corsa'), ('pesi', 'Pesi'), ('cyclette', 'Cyclette'), ('altro', 'Altro')], max_length=20),
        ),
    ]
