# Generated by Django 4.1.7 on 2023-05-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_workout_descrizione_workout_repetitions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='descrizione',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
