# Generated by Django 4.1.7 on 2023-05-24 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_workout_utente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='utente',
        ),
    ]
