# Generated by Django 4.1.7 on 2023-06-05 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obiettivi', '0009_alter_goalmodel_caloriesgoal'),
        ('workouts', '0008_alter_workout_utente'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='goal',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='obiettivi.goalmodel'),
        ),
    ]
