# Generated by Django 4.1.7 on 2023-06-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0009_workout_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='workout_type',
            field=models.CharField(choices=[('Running', 'Running'), ('Pesi', 'Pesi'), ('Cyclette', 'Cyclette'), ('Other', 'Other')], max_length=20),
        ),
    ]
